function [Lx_body,Ly_body,H_body,Lx_tail,Ly_tail,H_tail] = BerkeleyImpact_import7_Momentum(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [LX_BODY,LY_BODY,H_BODY,LX_TAIL,LY_TAIL,H_TAIL,VARNAME7] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [LX_BODY,LY_BODY,H_BODY,LX_TAIL,LY_TAIL,H_TAIL,VARNAME7] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Lx_body,Ly_body,H_body,Lx_tail,Ly_tail,H_tail,VarName7] =
%   importfile('BerkeleyImpact_TallBody.7',5, 205);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/09/25 13:04:56

%% Initialize variables.
if nargin<=2
    startRow = 5;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%14f%15f%15f%15f%15f%15f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Lx_body = dataArray{:, 1};
Ly_body = dataArray{:, 2};
H_body = dataArray{:, 3};
Lx_tail = dataArray{:, 4};
Ly_tail = dataArray{:, 5};
H_tail = dataArray{:, 6};
VarName7 = dataArray{:, 7};


